# Generated by Django 5.0.6 on 2024-06-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='Numero',
            field=models.CharField(max_length=15),
        ),
    ]
