# Generated by Django 5.0.6 on 2024-06-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_registro_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='Fecha_Ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='Fecha_Salida',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
