# Generated by Django 5.0.6 on 2024-07-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_registro_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='Fecha_Salida',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
